# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    # { device = "/dev/disk/by-uuid/2a5aef74-2add-4a1e-96f3-718fb476dee5";
    { device = "/dev/disk/by-uuid/ba678a3a-c335-4655-b7c7-141b03cc9ca5";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    # { device = "/dev/disk/by-uuid/6135-5926";
    { device = "/dev/disk/by-uuid/D2CE-E775";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  fileSystems."/home/jahan/ssd3" =
    { device = "/dev/disk/by-uuid/aedc2dcf-23d1-4d78-842f-2a313e41ec65";
      fsType = "xfs";
    };

  swapDevices =
    # [ { device = "/dev/disk/by-uuid/ab055306-61a2-413c-993d-3a4156d28f81"; }
    [ { device = "/dev/disk/by-uuid/38772735-1705-4d31-a722-8ba38f8a1bab"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp6s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
